# Generated by Django 4.1 on 2023-01-14 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0004_fotografia_data_fotografia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="data_fotografia",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 14, 17, 58, 45, 526680)
            ),
        ),
        migrations.AlterField(
            model_name="fotografia",
            name="foto",
            field=models.ImageField(blank=True, upload_to="fotos/%Y/%m/%d/"),
        ),
    ]
